import { 
  Document, Packer, Paragraph, TextRun, AlignmentType, PageNumber, ImageRun, BorderStyle, Table, TableRow, TableCell, WidthType
} from 'docx';
import QRCode from 'qrcode';

/**
 * Universal Digital Law Reporter (DLR) Editable DOCX Document Exporter
 * Generates an authentic Word document (.docx) with:
 * - Professional legal law report layout
 * - Exact court, parties, case number, headnote, and judgment body
 * - Running Word Footer with:
 *   - Bottom-Left: Generated by Digital Law Reporter | Date: DD/MM/YYYY, hh:mm am/pm | Page X of Y
 *   - Center: www.digilawreporter.in
 *   - Bottom-Right: Scannable Case QR Code
 */
export const downloadCaseAsDOCX = async (caseItem, showToast = () => {}) => {
  if (!caseItem) return;

  const caseId = caseItem.id || caseItem._id || '1';
  const canonicalUrl = `https://www.digilawreporter.in/case/${caseId}`;

  // 1. Generate QR Code Buffer
  let qrImageBuffer = null;
  try {
    const qrDataUrl = await QRCode.toDataURL(canonicalUrl, { 
      margin: 1, 
      width: 120,
      color: { dark: '#0F172A', light: '#FFFFFF' }
    });
    const base64Data = qrDataUrl.replace(/^data:image\/png;base64,/, '');
    const binaryStr = atob(base64Data);
    const len = binaryStr.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
      bytes[i] = binaryStr.charCodeAt(i);
    }
    qrImageBuffer = bytes;
  } catch (err) {
    console.error("QR Code generation for DOCX failed:", err);
  }

  // 2. Format Dynamic Generation Timestamp (DD/MM/YYYY, hh:mm am/pm)
  const now = new Date();
  const day = String(now.getDate()).padStart(2, '0');
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const year = now.getFullYear();
  const dateStr = `${day}/${month}/${year}`;

  let hours = now.getHours();
  const minutes = String(now.getMinutes()).padStart(2, '0');
  const ampm = hours >= 12 ? 'pm' : 'am';
  hours = hours % 12;
  hours = hours ? hours : 12;
  const timeStr = `${hours}:${minutes} ${ampm}`;
  const timestampText = `Date: ${dateStr}, ${timeStr}`;

  const docTitle = (caseItem.title || 'Judgment_Record').replace(/[^a-zA-Z0-9_\-]/g, '_');
  showToast(`Generating DLR Editable Word Document (.docx)...`);

  // 3. Extract Normalised Case Fields
  const citation = caseItem.citation || `${caseItem.year || '2024'} DLR (${caseItem.court || 'SC'})`;
  const court = caseItem.court_name || caseItem.court || 'SUPREME COURT OF INDIA';
  const rawTitle = caseItem.title || 'Untitled Case';
  let petitioner = caseItem.petitioner_name || caseItem.petitioner || '';
  let respondent = caseItem.respondent_name || caseItem.respondent || '';

  if (!petitioner && !respondent && rawTitle) {
    const splitMatch = rawTitle.split(/\s*(?:v\.?|vs\.?|VERSUS|V\/S)\s*/i);
    if (splitMatch.length === 2) {
      petitioner = splitMatch[0].trim();
      respondent = splitMatch[1].trim();
    }
  }

  const caseNumber = caseItem.case_number || caseItem.caseNumber || '';
  let formattedDate = '';
  if (caseItem.judgment_date || caseItem.judgmentDate) {
    try {
      const d = new Date(caseItem.judgment_date || caseItem.judgmentDate);
      formattedDate = d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
    } catch (e) {
      formattedDate = String(caseItem.judgment_date || '').trim();
    }
  }

  const bench = caseItem.bench || caseItem.coram || caseItem.author || '';
  const headNote = caseItem.head_note || caseItem.headnote || caseItem.summary || '';
  const fullContent = caseItem.content || caseItem.judgment_text || caseItem.judgmentText || '';
  const authorJudge = caseItem.author || caseItem.judge || '';

  // Clean Body Paragraphs
  const rawText = String(fullContent).replace(/<[^>]*>/g, '').trim();
  const paragraphsList = rawText.split(/\n\s*\n/).map(p => p.trim()).filter(Boolean);

  // 4. Build Document Structure
  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1080, bottom: 1200, left: 1080, right: 1080 }, // ~0.75 in margins
          },
        },
        footers: {
          default: new Footer({
            children: [
              new Table({
                width: { size: 100, type: WidthType.PERCENTAGE },
                borders: {
                  top: { style: BorderStyle.SINGLE, size: 4, color: "CBD5E1" },
                  bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                  left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                  right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                  insideHorizontal: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                  insideVertical: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                },
                rows: [
                  new TableRow({
                    children: [
                      // Left Column: Metadata
                      new TableCell({
                        width: { size: 45, type: WidthType.PERCENTAGE },
                        children: [
                          new Paragraph({
                            children: [
                              new TextRun({ text: "Generated by Digital Law Reporter", size: 15, font: "Calibri", color: "334155" }),
                            ],
                          }),
                          new Paragraph({
                            children: [
                              new TextRun({ text: timestampText, size: 15, font: "Calibri", color: "334155" }),
                            ],
                          }),
                          new Paragraph({
                            children: [
                              new TextRun({ text: "Page ", size: 15, bold: true, font: "Calibri", color: "334155" }),
                              new TextRun({ children: [PageNumber.CURRENT], size: 15, bold: true, font: "Calibri", color: "334155" }),
                              new TextRun({ text: " of ", size: 15, bold: true, font: "Calibri", color: "334155" }),
                              new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 15, bold: true, font: "Calibri", color: "334155" }),
                            ],
                          }),
                        ],
                      }),
                      // Center Column: Website URL (Horizontally Centered)
                      new TableCell({
                        width: { size: 35, type: WidthType.PERCENTAGE },
                        children: [
                          new Paragraph({
                            alignment: AlignmentType.CENTER,
                            children: [
                              new TextRun({ text: "www.digilawreporter.in", size: 13, font: "Calibri", color: "64748B" }),
                            ],
                          }),
                        ],
                      }),
                      // Right Column: QR Code
                      new TableCell({
                        width: { size: 20, type: WidthType.PERCENTAGE },
                        children: [
                          new Paragraph({
                            alignment: AlignmentType.RIGHT,
                            children: qrImageBuffer ? [
                              new ImageRun({
                                data: qrImageBuffer,
                                transformation: { width: 42, height: 42 },
                              }),
                            ] : [],
                          }),
                        ],
                      }),
                    ],
                  }),
                ],
              }),
            ],
          }),
        },
        children: [
          // Top Citation Header Line
          new Paragraph({
            alignment: AlignmentType.BOTH,
            children: [
              new TextRun({ text: citation, bold: true, size: 20, font: "Georgia" }),
              new TextRun({ text: "\t\t\t\t\t\t\t\tDIGI LAW REPORTER (DLR)", bold: true, size: 16, font: "Calibri", color: "64748B" }),
            ],
          }),
          new Paragraph({
            border: { bottom: { style: BorderStyle.SINGLE, size: 12, color: "0F172A" } },
            space: { after: 200 },
          }),

          // Court Header
          new Paragraph({
            alignment: AlignmentType.CENTER,
            space: { before: 200, after: 200 },
            children: [
              new TextRun({ text: `IN THE ${court.toUpperCase()}`, bold: true, size: 26, font: "Cinzel" }),
            ],
          }),

          // Parties Block
          petitioner && respondent ? new Paragraph({
            alignment: AlignmentType.CENTER,
            space: { before: 150, after: 150 },
            children: [
              new TextRun({ text: petitioner, bold: true, size: 22, font: "Georgia" }),
              new TextRun({ text: "  . . . Appellant(s);\n\n", italics: true, size: 18, font: "Calibri", color: "475569" }),
              new TextRun({ text: "Versus\n\n", italics: true, size: 18, font: "Georgia", color: "64748B" }),
              new TextRun({ text: respondent, bold: true, size: 22, font: "Georgia" }),
              new TextRun({ text: "  . . . Respondent(s).", italics: true, size: 18, font: "Calibri", color: "475569" }),
            ],
          }) : new Paragraph({
            alignment: AlignmentType.CENTER,
            space: { before: 150, after: 150 },
            children: [
              new TextRun({ text: rawTitle, bold: true, size: 22, font: "Georgia" }),
            ],
          }),

          // Case Number & Decided Date
          new Paragraph({
            alignment: AlignmentType.CENTER,
            space: { after: 150 },
            children: [
              new TextRun({ 
                text: `${caseNumber ? caseNumber : ''}${caseNumber && formattedDate ? ', ' : ''}${formattedDate ? `decided on ${formattedDate}` : ''}`, 
                italics: true, 
                size: 18, 
                font: "Georgia", 
                color: "334155" 
              }),
            ],
          }),

          // Bench Line
          bench ? new Paragraph({
            alignment: AlignmentType.CENTER,
            space: { after: 200 },
            children: [
              new TextRun({ text: "Before ", size: 18, font: "Georgia" }),
              new TextRun({ text: bench.toUpperCase(), bold: true, size: 18, font: "Calibri" }),
            ],
          }) : new Paragraph({ text: "" }),

          // Rule Line
          new Paragraph({
            border: { bottom: { style: BorderStyle.SINGLE, size: 8, color: "0F172A" } },
            space: { after: 240 },
          }),

          // Headnote Section
          headNote ? new Paragraph({
            children: [
              new TextRun({ text: "HEADNOTE\n", bold: true, size: 18, font: "Calibri", color: "0F172A" }),
              new TextRun({ text: String(headNote).replace(/<[^>]*>/g, '').trim(), size: 20, font: "Georgia", color: "1E293B" }),
            ],
            space: { after: 240 },
          }) : new Paragraph({ text: "" }),

          headNote ? new Paragraph({
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "64748B" } },
            space: { after: 240 },
          }) : new Paragraph({ text: "" }),

          // Judgment Delivery Line
          authorJudge ? new Paragraph({
            children: [
              new TextRun({ text: "The Judgment of the Court was delivered by\n", italics: true, size: 18, font: "Georgia" }),
              new TextRun({ text: `${authorJudge.toUpperCase()}, J.—`, bold: true, size: 18, font: "Calibri", color: "0F172A" }),
            ],
            space: { after: 200 },
          }) : new Paragraph({
            children: [
              new TextRun({ text: "JUDGMENT", bold: true, size: 18, font: "Calibri", color: "0F172A" }),
            ],
            space: { after: 200 },
          }),

          // Body Paragraphs
          ...paragraphsList.map(para => new Paragraph({
            alignment: AlignmentType.JUSTIFY,
            space: { after: 180, line: 360 }, // Comfortable line height & spacing
            children: [
              new TextRun({ text: para, size: 21, font: "Georgia", color: "0F172A" }),
            ],
          })),
        ],
      },
    ],
  });

  // 5. Generate Blob & Download File
  try {
    const blob = await Packer.toBlob(doc);
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `DLR_${docTitle}.docx`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(link.href);
    showToast(`Word Document (.docx) downloaded successfully!`);
  } catch (err) {
    console.error("DOCX generation error:", err);
    showToast("DOCX export failed");
  }
};
